# Generated by Django 5.0.6 on 2024-09-10 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataqualitymodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('semantic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('description', models.TextField()),
                ('owner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('description', models.TextField()),
                ('author', models.TextField()),
                ('last_update', models.DateField()),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAtHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('use', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('characteristics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DQMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('description', models.TextField()),
                ('describe', models.TextField()),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dq_metadata', to='dataqualitymodel.dqmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('purpose', models.TextField()),
                ('imposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_requirements', to='contextmodel.taskathand')),
            ],
        ),
        migrations.CreateModel(
            name='DataFiltering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('description', models.TextField()),
                ('addressed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_filtering_requirements', to='contextmodel.taskathand')),
                ('asigned_to', models.ManyToManyField(related_name='data_filtering_requirements', to='contextmodel.usertype')),
            ],
        ),
        migrations.AddField(
            model_name='taskathand',
            name='assignedTo',
            field=models.ManyToManyField(related_name='tasks_at_hand', to='contextmodel.usertype'),
        ),
        migrations.CreateModel(
            name='DQRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('description', models.TextField()),
                ('references', models.ManyToManyField(blank=True, related_name='referenced_by', to='contextmodel.datafiltering')),
                ('imposed_by', models.ManyToManyField(related_name='dq_requirements', to='contextmodel.usertype')),
            ],
        ),
    ]
