# Generated by Django 5.0.6 on 2024-10-08 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DQDimensionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('semantic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finished', 'Finished')], default='draft', max_length=10)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DQFactorBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('semantic', models.TextField()),
                ('facetOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='dqmodel.dqdimensionbase')),
            ],
        ),
        migrations.CreateModel(
            name='DQMetricBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('purpose', models.TextField()),
                ('granularity', models.CharField(max_length=100)),
                ('resultDomain', models.CharField(max_length=100)),
                ('measures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dqmodel.dqfactorbase')),
            ],
        ),
        migrations.CreateModel(
            name='DQMethodBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('inputDataType', models.CharField(max_length=100)),
                ('outputDataType', models.CharField(max_length=100)),
                ('algorithm', models.TextField()),
                ('implements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='dqmodel.dqmetricbase')),
            ],
        ),
        migrations.CreateModel(
            name='DQModelDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_dimensions', to='dqmodel.dqdimensionbase')),
                ('dq_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_dimensions', to='dqmodel.dqmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DQModelFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='dqmodel.dqmodeldimension')),
                ('dq_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_factors', to='dqmodel.dqmodel')),
                ('factor_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_factors', to='dqmodel.dqfactorbase')),
            ],
        ),
        migrations.CreateModel(
            name='DQModelMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dq_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_methods', to='dqmodel.dqmodel')),
                ('method_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_methods', to='dqmodel.dqmethodbase')),
            ],
        ),
        migrations.CreateModel(
            name='AggregationDQMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appliedTo', models.CharField(max_length=100)),
                ('associatedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_applied_methods', to='dqmodel.dqmodelmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DQModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dq_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_metrics', to='dqmodel.dqmodel')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dqmodel.dqmodelfactor')),
                ('metric_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_metrics', to='dqmodel.dqmetricbase')),
            ],
        ),
        migrations.AddField(
            model_name='dqmodelmethod',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='dqmodel.dqmodelmetric'),
        ),
        migrations.CreateModel(
            name='MeasurementDQMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appliedTo', models.CharField(max_length=100)),
                ('associatedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_applied_methods', to='dqmodel.dqmodelmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
