# Generated by Django 5.0.6 on 2025-07-26 20:14
# Generated by Django 5.0.6 on 2025-07-26 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models

#python manage.py migrate dqmodel 0002 --database=metadata_db 

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dqmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DQModelExecution',
            fields=[
                ('execution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dq_model_id', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='in_progress', max_length=50)),
            ],
            options={
                'db_table': 'dq_modelexecution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DQMethodExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('dq_value', models.JSONField(default=dict)),
                ('result_type', models.CharField(default='single', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('assessment_thresholds', models.JSONField(blank=True, default=list)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_results', to='dqmodel.dqmodelexecution')),
            ],
            options={
                'db_table': 'dq_method_execution_result',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExecutionColumnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=255)),
                ('column_id', models.IntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('dq_value', models.FloatField(blank=True, null=True)),
                ('assessment_score', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_results', to='dqmodel.dqmethodexecutionresult')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionRowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_method_id', models.IntegerField()),
                ('table_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=255)),
                ('column_id', models.IntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=255)),
                ('row_id', models.CharField(max_length=255)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('dq_value', models.FloatField(blank=True, null=True)),
                ('assessment_score', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_results', to='dqmodel.dqmethodexecutionresult')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionTableResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=255)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('dq_value', models.FloatField(blank=True, null=True)),
                ('assessment_score', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_results', to='dqmodel.dqmethodexecutionresult')),
            ],
        ),
        migrations.AddIndex(
            model_name='dqmethodexecutionresult',
            index=models.Index(fields=['content_type', 'object_id'], name='dq_method_e_content_3501e8_idx'),
        ),
        migrations.AddIndex(
            model_name='dqmethodexecutionresult',
            index=models.Index(fields=['execution'], name='dq_method_e_executi_254527_idx'),
        ),
        migrations.AddIndex(
            model_name='executioncolumnresult',
            index=models.Index(fields=['column_id'], name='dqmodel_exe_column__e2a626_idx'),
        ),
        migrations.AddIndex(
            model_name='executioncolumnresult',
            index=models.Index(fields=['table_id', 'column_id'], name='dqmodel_exe_table_i_1adfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='executionrowresult',
            index=models.Index(fields=['row_id'], name='dqmodel_exe_row_id_94651e_idx'),
        ),
        migrations.AddIndex(
            model_name='executionrowresult',
            index=models.Index(fields=['table_id', 'row_id'], name='dqmodel_exe_table_i_654d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='executionrowresult',
            index=models.Index(fields=['applied_method_id'], name='dqmodel_exe_applied_3854be_idx'),
        ),
        migrations.AddIndex(
            model_name='executiontableresult',
            index=models.Index(fields=['table_id'], name='dqmodel_exe_table_i_f9ce6c_idx'),
        ),
        migrations.AddIndex(
            model_name='executiontableresult',
            index=models.Index(fields=['execution_result'], name='dqmodel_exe_executi_44fca1_idx'),
        ),
    ]
