# Generated by Django 5.0.6 on 2024-10-08 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqmodelfactor',
            name='dimension',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='dqmodel.dqmodeldimension'),
        ),
    ]
