# Generated by Django 5.0.6 on 2024-10-08 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0002_alter_dqmodelfactor_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqmodelmethod',
            name='metric',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='dqmodel.dqmodelmetric'),
        ),
        migrations.AlterField(
            model_name='dqmodelmetric',
            name='factor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dqmodel.dqmodelfactor'),
        ),
    ]
