# Generated by Django 5.0.6 on 2024-10-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0003_alter_dqmodelmethod_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqmodel',
            name='finished_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
