# Generated by Django 5.0.6 on 2024-10-09 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0004_alter_dqmodel_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmodel',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='dqmodel.dqmodel'),
        ),
    ]
