# Generated by Django 5.0.6 on 2024-10-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0005_dqmodel_previous_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmodeldimension',
            name='context_components',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
