# Generated by Django 5.0.6 on 2025-01-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0011_load_default_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioritizedDqProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=-1)),
                ('priority_type', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=6)),
                ('date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('dq_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioritized_problems', to='dqmodel.dqmodel')),
            ],
            options={
                'unique_together': {('dq_model', 'description')},
            },
        ),
    ]
