# Generated by Django 5.0.6 on 2025-01-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0012_prioritizeddqproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritizeddqproblem',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prioritizeddqproblem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
