# Generated by Django 5.0.6 on 2025-01-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0013_prioritizeddqproblem_is_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmodelfactor',
            name='context_components',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
