# Generated by Django 5.0.6 on 2024-08-05 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DQDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semantic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DQMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inputDataType', models.CharField(max_length=100)),
                ('outputDataType', models.CharField(max_length=100)),
                ('algorithm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DQFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semantic', models.TextField()),
                ('facetOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='dataqualitymodel.dqdimension')),
                ('fIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='dataqualitymodel.dqmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AggregationDQMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appliedTo', models.CharField(max_length=100)),
                ('associatedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_applied_methods', to='dataqualitymodel.dqmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DQMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('granularity', models.CharField(max_length=100)),
                ('resultDomain', models.CharField(max_length=100)),
                ('measures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dataqualitymodel.dqfactor')),
                ('mIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dataqualitymodel.dqmodel')),
            ],
        ),
        migrations.AddField(
            model_name='dqmethod',
            name='implements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='dataqualitymodel.dqmetric'),
        ),
        migrations.AddField(
            model_name='dqmethod',
            name='mtIn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='dataqualitymodel.dqmodel'),
        ),
        migrations.AddField(
            model_name='dqdimension',
            name='dIn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='dataqualitymodel.dqmodel'),
        ),
        migrations.CreateModel(
            name='MeasurementDQMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appliedTo', models.CharField(max_length=100)),
                ('associatedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_applied_methods', to='dataqualitymodel.dqmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
