# Generated by Django 5.0.6 on 2024-09-11 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataqualitymodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
