# Generated by Django 5.0.6 on 2024-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataqualitymodel', '0002_dqmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finished', 'Finished')], default='draft', max_length=10),
        ),
    ]
