# Generated by Django 5.0.6 on 2024-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataqualitymodel', '0003_dqmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmodel',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
