# Generated by Django 5.0.6 on 2024-09-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataqualitymodel', '0004_dqmodel_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dqmodel',
            name='finished_at',
        ),
    ]
