# Generated by Django 5.0.6 on 2024-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataqualitymodel', '0005_remove_dqmodel_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmodel',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
