# Generated by Django 5.0.6 on 2024-09-10 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('context_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contextmodel.contextmodel')),
                ('dqmodel_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataqualitymodel.dqmodel')),
            ],
            options={
                'unique_together': {('context_version', 'dqmodel_version')},
            },
        ),
    ]
