# Generated by Django 5.0.6 on 2024-10-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqmodel', '0005_dqmodel_previous_version'),
        ('project', '0003_project_description_project_stage_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dqmodel_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqmodel.dqmodel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
