--
-- PostgreSQL database dump
--

-- Dumped from database version 13.10
-- Dumped by pg_dump version 13.10

-- Started on 2025-09-06 21:30:26

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 200 (class 1259 OID 322685)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 322688)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 322690)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 322696)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 322698)
-- Name: dq_method_execution_result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dq_method_execution_result (
    id bigint NOT NULL,
    object_id integer NOT NULL,
    executed_at timestamp with time zone NOT NULL,
    dq_value jsonb NOT NULL,
    result_type character varying(20) NOT NULL,
    details jsonb NOT NULL,
    assessment_thresholds jsonb NOT NULL,
    assessed_at timestamp with time zone,
    content_type_id integer NOT NULL,
    execution_id uuid NOT NULL,
    CONSTRAINT dq_method_execution_result_object_id_check CHECK ((object_id >= 0))
);


ALTER TABLE public.dq_method_execution_result OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 322705)
-- Name: dq_method_execution_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dq_method_execution_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dq_method_execution_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 322707)
-- Name: dq_modelexecution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dq_modelexecution (
    execution_id uuid NOT NULL,
    dq_model_id integer NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    status character varying(50) NOT NULL
);


ALTER TABLE public.dq_modelexecution OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 322710)
-- Name: dqmodel_executioncolumnresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dqmodel_executioncolumnresult (
    id bigint NOT NULL,
    table_id integer NOT NULL,
    table_name character varying(255) NOT NULL,
    column_id integer NOT NULL,
    column_name character varying(255) NOT NULL,
    executed_at timestamp with time zone NOT NULL,
    dq_value double precision,
    assessment_score character varying(100),
    execution_result_id bigint NOT NULL
);


ALTER TABLE public.dqmodel_executioncolumnresult OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 322716)
-- Name: dqmodel_executioncolumnresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dqmodel_executioncolumnresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dqmodel_executioncolumnresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 322718)
-- Name: dqmodel_executionrowresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dqmodel_executionrowresult (
    id bigint NOT NULL,
    applied_method_id integer NOT NULL,
    table_id integer NOT NULL,
    table_name character varying(255) NOT NULL,
    column_id integer,
    column_name character varying(255) NOT NULL,
    row_id character varying(255) NOT NULL,
    executed_at timestamp with time zone NOT NULL,
    dq_value double precision,
    assessment_score character varying(100),
    execution_result_id bigint NOT NULL
);


ALTER TABLE public.dqmodel_executionrowresult OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 322724)
-- Name: dqmodel_executionrowresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dqmodel_executionrowresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dqmodel_executionrowresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 322726)
-- Name: dqmodel_executiontableresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dqmodel_executiontableresult (
    id bigint NOT NULL,
    table_id integer NOT NULL,
    table_name character varying(255) NOT NULL,
    executed_at timestamp with time zone NOT NULL,
    dq_value double precision,
    assessment_score character varying(100),
    execution_result_id bigint NOT NULL
);


ALTER TABLE public.dqmodel_executiontableresult OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 322729)
-- Name: dqmodel_executiontableresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dqmodel_executiontableresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dqmodel_executiontableresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3053 (class 0 OID 322685)
-- Dependencies: 200
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
\.


--
-- TOC entry 3055 (class 0 OID 322690)
-- Dependencies: 202
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
\.


--
-- TOC entry 3057 (class 0 OID 322698)
-- Dependencies: 204
-- Data for Name: dq_method_execution_result; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dq_method_execution_result (id, object_id, executed_at, dq_value, result_type, details, assessment_thresholds, assessed_at, content_type_id, execution_id) FROM stdin;
\.


--
-- TOC entry 3059 (class 0 OID 322707)
-- Dependencies: 206
-- Data for Name: dq_modelexecution; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dq_modelexecution (execution_id, dq_model_id, started_at, completed_at, status) FROM stdin;
\.


--
-- TOC entry 3060 (class 0 OID 322710)
-- Dependencies: 207
-- Data for Name: dqmodel_executioncolumnresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dqmodel_executioncolumnresult (id, table_id, table_name, column_id, column_name, executed_at, dq_value, assessment_score, execution_result_id) FROM stdin;
\.


--
-- TOC entry 3062 (class 0 OID 322718)
-- Dependencies: 209
-- Data for Name: dqmodel_executionrowresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dqmodel_executionrowresult (id, applied_method_id, table_id, table_name, column_id, column_name, row_id, executed_at, dq_value, assessment_score, execution_result_id) FROM stdin;
\.


--
-- TOC entry 3064 (class 0 OID 322726)
-- Dependencies: 211
-- Data for Name: dqmodel_executiontableresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dqmodel_executiontableresult (id, table_id, table_name, executed_at, dq_value, assessment_score, execution_result_id) FROM stdin;
\.


--
-- TOC entry 3071 (class 0 OID 0)
-- Dependencies: 201
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 1, false);


--
-- TOC entry 3072 (class 0 OID 0)
-- Dependencies: 203
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 1, false);


--
-- TOC entry 3073 (class 0 OID 0)
-- Dependencies: 205
-- Name: dq_method_execution_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dq_method_execution_result_id_seq', 1, false);


--
-- TOC entry 3074 (class 0 OID 0)
-- Dependencies: 208
-- Name: dqmodel_executioncolumnresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dqmodel_executioncolumnresult_id_seq', 1, false);


--
-- TOC entry 3075 (class 0 OID 0)
-- Dependencies: 210
-- Name: dqmodel_executionrowresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dqmodel_executionrowresult_id_seq', 1, false);


--
-- TOC entry 3076 (class 0 OID 0)
-- Dependencies: 212
-- Name: dqmodel_executiontableresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dqmodel_executiontableresult_id_seq', 1, false);


--
-- TOC entry 2890 (class 2606 OID 322739)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 2892 (class 2606 OID 322741)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 2894 (class 2606 OID 322743)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 2900 (class 2606 OID 322745)
-- Name: dq_method_execution_result dq_method_execution_result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dq_method_execution_result
    ADD CONSTRAINT dq_method_execution_result_pkey PRIMARY KEY (id);


--
-- TOC entry 2902 (class 2606 OID 322747)
-- Name: dq_modelexecution dq_modelexecution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dq_modelexecution
    ADD CONSTRAINT dq_modelexecution_pkey PRIMARY KEY (execution_id);


--
-- TOC entry 2907 (class 2606 OID 322749)
-- Name: dqmodel_executioncolumnresult dqmodel_executioncolumnresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dqmodel_executioncolumnresult
    ADD CONSTRAINT dqmodel_executioncolumnresult_pkey PRIMARY KEY (id);


--
-- TOC entry 2913 (class 2606 OID 322751)
-- Name: dqmodel_executionrowresult dqmodel_executionrowresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dqmodel_executionrowresult
    ADD CONSTRAINT dqmodel_executionrowresult_pkey PRIMARY KEY (id);


--
-- TOC entry 2918 (class 2606 OID 322753)
-- Name: dqmodel_executiontableresult dqmodel_executiontableresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dqmodel_executiontableresult
    ADD CONSTRAINT dqmodel_executiontableresult_pkey PRIMARY KEY (id);


--
-- TOC entry 2895 (class 1259 OID 322754)
-- Name: dq_method_e_content_3501e8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dq_method_e_content_3501e8_idx ON public.dq_method_execution_result USING btree (content_type_id, object_id);


--
-- TOC entry 2896 (class 1259 OID 322755)
-- Name: dq_method_e_executi_254527_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dq_method_e_executi_254527_idx ON public.dq_method_execution_result USING btree (execution_id);


--
-- TOC entry 2897 (class 1259 OID 322756)
-- Name: dq_method_execution_result_content_type_id_43b44923; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dq_method_execution_result_content_type_id_43b44923 ON public.dq_method_execution_result USING btree (content_type_id);


--
-- TOC entry 2898 (class 1259 OID 322757)
-- Name: dq_method_execution_result_execution_id_089f2686; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dq_method_execution_result_execution_id_089f2686 ON public.dq_method_execution_result USING btree (execution_id);


--
-- TOC entry 2908 (class 1259 OID 322758)
-- Name: dqmodel_exe_applied_3854be_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_exe_applied_3854be_idx ON public.dqmodel_executionrowresult USING btree (applied_method_id);


--
-- TOC entry 2903 (class 1259 OID 322759)
-- Name: dqmodel_exe_column__e2a626_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_exe_column__e2a626_idx ON public.dqmodel_executioncolumnresult USING btree (column_id);


--
-- TOC entry 2914 (class 1259 OID 322760)
-- Name: dqmodel_exe_executi_44fca1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_exe_executi_44fca1_idx ON public.dqmodel_executiontableresult USING btree (execution_result_id);


--
-- TOC entry 2909 (class 1259 OID 322761)
-- Name: dqmodel_exe_row_id_94651e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_exe_row_id_94651e_idx ON public.dqmodel_executionrowresult USING btree (row_id);


--
-- TOC entry 2904 (class 1259 OID 322762)
-- Name: dqmodel_exe_table_i_1adfcd_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_exe_table_i_1adfcd_idx ON public.dqmodel_executioncolumnresult USING btree (table_id, column_id);


--
-- TOC entry 2910 (class 1259 OID 322763)
-- Name: dqmodel_exe_table_i_654d5f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_exe_table_i_654d5f_idx ON public.dqmodel_executionrowresult USING btree (table_id, row_id);


--
-- TOC entry 2915 (class 1259 OID 322764)
-- Name: dqmodel_exe_table_i_f9ce6c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_exe_table_i_f9ce6c_idx ON public.dqmodel_executiontableresult USING btree (table_id);


--
-- TOC entry 2905 (class 1259 OID 322765)
-- Name: dqmodel_executioncolumnresult_execution_result_id_78660346; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_executioncolumnresult_execution_result_id_78660346 ON public.dqmodel_executioncolumnresult USING btree (execution_result_id);


--
-- TOC entry 2911 (class 1259 OID 322766)
-- Name: dqmodel_executionrowresult_execution_result_id_8a9fec31; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_executionrowresult_execution_result_id_8a9fec31 ON public.dqmodel_executionrowresult USING btree (execution_result_id);


--
-- TOC entry 2916 (class 1259 OID 322767)
-- Name: dqmodel_executiontableresult_execution_result_id_bbb8ed28; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dqmodel_executiontableresult_execution_result_id_bbb8ed28 ON public.dqmodel_executiontableresult USING btree (execution_result_id);


--
-- TOC entry 2919 (class 2606 OID 322768)
-- Name: dq_method_execution_result dq_method_execution__execution_id_089f2686_fk_dq_modele; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dq_method_execution_result
    ADD CONSTRAINT dq_method_execution__execution_id_089f2686_fk_dq_modele FOREIGN KEY (execution_id) REFERENCES public.dq_modelexecution(execution_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 2920 (class 2606 OID 322773)
-- Name: dqmodel_executioncolumnresult dqmodel_executioncol_execution_result_id_78660346_fk_dq_method; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dqmodel_executioncolumnresult
    ADD CONSTRAINT dqmodel_executioncol_execution_result_id_78660346_fk_dq_method FOREIGN KEY (execution_result_id) REFERENCES public.dq_method_execution_result(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 2921 (class 2606 OID 322778)
-- Name: dqmodel_executionrowresult dqmodel_executionrow_execution_result_id_8a9fec31_fk_dq_method; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dqmodel_executionrowresult
    ADD CONSTRAINT dqmodel_executionrow_execution_result_id_8a9fec31_fk_dq_method FOREIGN KEY (execution_result_id) REFERENCES public.dq_method_execution_result(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 2922 (class 2606 OID 322783)
-- Name: dqmodel_executiontableresult dqmodel_executiontab_execution_result_id_bbb8ed28_fk_dq_method; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dqmodel_executiontableresult
    ADD CONSTRAINT dqmodel_executiontab_execution_result_id_bbb8ed28_fk_dq_method FOREIGN KEY (execution_result_id) REFERENCES public.dq_method_execution_result(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-09-06 21:30:29

--
-- PostgreSQL database dump complete
--

